version: 0.2

phases:
  install:
    commands:
      - npm install serverless -g
  build:
    commands:
      - npm install
      - export REST_API_ID=$( \
          aws apigateway get-rest-apis \
            --query 'items[?name==`api-dev.forgotpw.com`].[id]' \
            --output text)
      - export ROOT_RESOURCE_ID=$( \
          aws apigateway get-resources \
            --rest-api-id $REST_API_ID \
            --query 'items[?path==`/`].[id]' \
            --output text)
      - export V1_RESOURCE_ID=$( \
          aws apigateway get-resources \
            --rest-api-id $REST_API_ID \
            --query 'items[?path==`/v1`].[id]' \
            --output text)
      - sls invoke test
