version: 0.2

phases:
  install:
    commands:
      - npm install serverless -g
  build:
    commands:
      - npm install
      - chmod +x ./exports.sh
      - . ./exports.sh api-dev default
      - sls invoke test
