version: 0.2

phases:
  install:
    commands:
      - echo Installing prerequisites...
      - npm install serverless -g
      - aws --version
  build:
    commands:
      - echo Exporting environment variables
      - source exports.sh api-dev default
      - echo Invoking test
      - sls invoke test
