const config = {
  AWS_REGION: process.env.AWS_REGION || 'us-east-1',
  USERTOKEN_HASH_HMAC: process.env.USERTOKEN_HASH_HMAC,
  USERTOKENS_S3_BUCKET: process.env.USERTOKENS_S3_BUCKET, 
  STORE_SNS_TOPIC_NAME: process.env.STORE_SNS_TOPIC_NAME,
  RETRIEVE_SNS_TOPIC_NAME: process.env.RETRIEVE_SNS_TOPIC_NAME,
  SENDCODE_SNS_TOPIC_NAME: process.env.SENDCODE_SNS_TOPIC_NAME,
  NUKEACCOUNT_SNS_TOPIC_NAME: process.env.NUKEACCOUNT_SNS_TOPIC_NAME,
  CODE_INVALIDCOUNT_MAX: process.env.CODE_INVALIDCOUNT_MAX,
  AUTHREQ_S3_BUCKET: process.env.AUTHREQ_S3_BUCKET,
  AUTHREQ_EXPIRE_MINS: process.env.AUTHREQ_EXPIRE_MINS,
  LOG_LEVEL: process.env.LOG_LEVEL
}

module.exports = config
